### ISSUE TITLE
Wheel motor encoders

### ISSUE THREAD

**Issue by kbickham** [EliasKotlyar/IlifeX5Disassembly#2]
You're have the only information I've found on this board. Just curious if you've tinkered and by chance figured out the wiring on these wheel motor encoders?

**Comment by EliasKotlyar** [comment]
Hey

No i havent figured out the wiring, but by looking at the wiring harness, i suppose following may be the case:
1. Red = Plus
2. Black = Ground
3. Yellow/Green/White - one of them should be connected to ground(just compare the input to Black). Other 2 should be the Hall Sensors.

**Comment by kbickham** [comment]
Elias,

Thank you so much, if you like... I didn't mean to post in an issue, I can
go click it completed if you like. I do wonder... that open 4 hole header
(labeled J11) ..do you know if this is a service header? I would like to
try and interact with the mcu, but haven't started probing yet. Thanks
again!

Kris

**Comment by EliasKotlyar** [comment]
It should be a service header, however i am not sure which protocol the MCU is speaking. 
I suppose it might be UART. I would suggest that you try to debug it using following Tutorial:
https://jcjc-dev.com/2016/04/08/reversing-huawei-router-1-find-uart/

**Comment by kbickham** [comment]
I just tested, it's not UART..it's spi. One pin on the header I believe (swclk) has usart2_tx function though. I have my findings up here :https://github.com/kbickham/iLife_Robotic_Vaccum_v3s_Reverse_Engineer/blob/master/README.md
